/* CVS $Id: $ */
package example; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from file:src/example/geonames.owl 
 * @author Auto-generated by schemagen on 01 Dec 2007 23:12 
 */
public class GeonamesVocabulary {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.geonames.org/ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Links to an RDF document containing the descriptions of children features</p> */
    public static final ObjectProperty childrenFeatures = m_model.createObjectProperty( "http://www.geonames.org/ontology#childrenFeatures" );
    
    /** <p>Classification of a feature against a Concept, either defined by its URI taken 
     *  from any Concept Scheme, or by a blank node description.</p>
     */
    public static final ObjectProperty tag = m_model.createObjectProperty( "http://www.geonames.org/ontology#tag" );
    
    /** <p>Indicates that the subject resource is located in the object feature</p> */
    public static final ObjectProperty locatedIn = m_model.createObjectProperty( "http://www.geonames.org/ontology#locatedIn" );
    
    /** <p>Type of the feature, as defined in geonames taxonomy.</p> */
    public static final ObjectProperty featureCode = m_model.createObjectProperty( "http://www.geonames.org/ontology#featureCode" );
    
    /** <p>Links to an RDF document containing the descriptions of neighbouring features. 
     *  Applies when the feature has definite boarders.</p>
     */
    public static final ObjectProperty neighbouringFeatures = m_model.createObjectProperty( "http://www.geonames.org/ontology#neighbouringFeatures" );
    
    /** <p>Links to an RDF document containing the descriptions of nearby features</p> */
    public static final ObjectProperty nearbyFeatures = m_model.createObjectProperty( "http://www.geonames.org/ontology#nearbyFeatures" );
    
    /** <p>A feature parent of the current one, in either administrative or physical 
     *  subdivision.</p>
     */
    public static final ObjectProperty parentFeature = m_model.createObjectProperty( "http://www.geonames.org/ontology#parentFeature" );
    
    /** <p>A Wikipedia article of which subject is the resource.</p> */
    public static final ObjectProperty wikipediaArticle = m_model.createObjectProperty( "http://www.geonames.org/ontology#wikipediaArticle" );
    
    /** <p>A country in the ISO country list</p> */
    public static final ObjectProperty inCountry = m_model.createObjectProperty( "http://www.geonames.org/ontology#inCountry" );
    
    /** <p>A geonames map centered on the feature.</p> */
    public static final ObjectProperty locationMap = m_model.createObjectProperty( "http://www.geonames.org/ontology#locationMap" );
    
    /** <p>A feature close to the reference feature</p> */
    public static final ObjectProperty nearby = m_model.createObjectProperty( "http://www.geonames.org/ontology#nearby" );
    
    /** <p>A feature sharing a common boarder with the reference feature</p> */
    public static final ObjectProperty neighbour = m_model.createObjectProperty( "http://www.geonames.org/ontology#neighbour" );
    
    /** <p>The main category of the feature, as defined in geonames taxonomy.</p> */
    public static final ObjectProperty featureClass = m_model.createObjectProperty( "http://www.geonames.org/ontology#featureClass" );
    
    public static final DatatypeProperty postalCode = m_model.createDatatypeProperty( "http://www.geonames.org/ontology#postalCode" );
    
    public static final DatatypeProperty population = m_model.createDatatypeProperty( "http://www.geonames.org/ontology#population" );
    
    /** <p>A name in an official local language</p> */
    public static final DatatypeProperty officialName = m_model.createDatatypeProperty( "http://www.geonames.org/ontology#officialName" );
    
    /** <p>The preferred name of the feature.</p> */
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://www.geonames.org/ontology#name" );
    
    /** <p>An alternate name for a feature</p> */
    public static final DatatypeProperty alternateName = m_model.createDatatypeProperty( "http://www.geonames.org/ontology#alternateName" );
    
    /** <p>A feature code.</p> */
    public static final OntClass Code = m_model.createClass( "http://www.geonames.org/ontology#Code" );
    
    /** <p>A country as defined at http://www.geonames.org/countries</p> */
    public static final OntClass Country = m_model.createClass( "http://www.geonames.org/ontology#Country" );
    
    /** <p>A Document containing RDF description of one or several features.</p> */
    public static final OntClass RDFData = m_model.createClass( "http://www.geonames.org/ontology#RDFData" );
    
    /** <p>A class of features.</p> */
    public static final OntClass Class = m_model.createClass( "http://www.geonames.org/ontology#Class" );
    
    /** <p>A Web page displaying a map</p> */
    public static final OntClass Map = m_model.createClass( "http://www.geonames.org/ontology#Map" );
    
    /** <p>A Wikipedia article</p> */
    public static final OntClass WikipediaArticle = m_model.createClass( "http://www.geonames.org/ontology#WikipediaArticle" );
    
    /** <p>A geographical object uniquely defined by its geonames id.</p> */
    public static final OntClass Feature = m_model.createClass( "http://www.geonames.org/ontology#Feature" );
    
    public static final Individual S_CVNT = m_model.createIndividual( "http://www.geonames.org/ontology#S.CVNT", Code );
    
    public static final Individual S_ANS = m_model.createIndividual( "http://www.geonames.org/ontology#S.ANS", Code );
    
    public static final Individual U_VALU = m_model.createIndividual( "http://www.geonames.org/ontology#U.VALU", Code );
    
    public static final Individual T_RDGE = m_model.createIndividual( "http://www.geonames.org/ontology#T.RDGE", Code );
    
    public static final Individual T_CRQ = m_model.createIndividual( "http://www.geonames.org/ontology#T.CRQ", Code );
    
    public static final Individual S_MFGC = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGC", Code );
    
    public static final Individual H_CAPG = m_model.createIndividual( "http://www.geonames.org/ontology#H.CAPG", Code );
    
    public static final Individual S_MFGB = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGB", Code );
    
    public static final Individual S_STPS = m_model.createIndividual( "http://www.geonames.org/ontology#S.STPS", Code );
    
    public static final Individual H_HBR = m_model.createIndividual( "http://www.geonames.org/ontology#H.HBR", Code );
    
    public static final Individual T_BCH = m_model.createIndividual( "http://www.geonames.org/ontology#T.BCH", Code );
    
    public static final Individual S_WTRW = m_model.createIndividual( "http://www.geonames.org/ontology#S.WTRW", Code );
    
    public static final Individual H_STRT = m_model.createIndividual( "http://www.geonames.org/ontology#H.STRT", Code );
    
    public static final Individual T_BLHL = m_model.createIndividual( "http://www.geonames.org/ontology#T.BLHL", Code );
    
    public static final Individual L_MILB = m_model.createIndividual( "http://www.geonames.org/ontology#L.MILB", Code );
    
    public static final Individual U_RAVU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RAVU", Code );
    
    public static final Individual T_SBED = m_model.createIndividual( "http://www.geonames.org/ontology#T.SBED", Code );
    
    public static final Individual T_ATOL = m_model.createIndividual( "http://www.geonames.org/ontology#T.ATOL", Code );
    
    public static final Individual U_MDVU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MDVU", Code );
    
    public static final Individual S_PAL = m_model.createIndividual( "http://www.geonames.org/ontology#S.PAL", Code );
    
    public static final Individual S_MLM = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLM", Code );
    
    public static final Individual L_SALT = m_model.createIndividual( "http://www.geonames.org/ontology#L.SALT", Code );
    
    public static final Individual T_SPIT = m_model.createIndividual( "http://www.geonames.org/ontology#T.SPIT", Code );
    
    public static final Individual H_RF = m_model.createIndividual( "http://www.geonames.org/ontology#H.RF", Code );
    
    public static final Individual S_AMTH = m_model.createIndividual( "http://www.geonames.org/ontology#S.AMTH", Code );
    
    public static final Individual H_MFGN = m_model.createIndividual( "http://www.geonames.org/ontology#H.MFGN", Code );
    
    public static final Individual U_TRGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TRGU", Code );
    
    public static final Individual H_PNDSF = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDSF", Code );
    
    public static final Individual S_ZOO = m_model.createIndividual( "http://www.geonames.org/ontology#S.ZOO", Code );
    
    public static final Individual S_MFG = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFG", Code );
    
    public static final Individual V_VINS = m_model.createIndividual( "http://www.geonames.org/ontology#V.VINS", Code );
    
    public static final Individual S_MLO = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLO", Code );
    
    public static final Individual T_ISLM = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISLM", Code );
    
    public static final Individual S_WHRF = m_model.createIndividual( "http://www.geonames.org/ontology#S.WHRF", Code );
    
    public static final Individual S_RHSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.RHSE", Code );
    
    public static final Individual T_BCHS = m_model.createIndividual( "http://www.geonames.org/ontology#T.BCHS", Code );
    
    public static final Individual U_CDAU = m_model.createIndividual( "http://www.geonames.org/ontology#U.CDAU", Code );
    
    public static final Individual S_MUS = m_model.createIndividual( "http://www.geonames.org/ontology#S.MUS", Code );
    
    public static final Individual S_MLWTR = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLWTR", Code );
    
    public static final Individual H_FJD = m_model.createIndividual( "http://www.geonames.org/ontology#H.FJD", Code );
    
    public static final Individual S_OILJ = m_model.createIndividual( "http://www.geonames.org/ontology#S.OILJ", Code );
    
    public static final Individual S_GHSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.GHSE", Code );
    
    public static final Individual T_ISL = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISL", Code );
    
    public static final Individual S_MFGM = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGM", Code );
    
    public static final Individual T_CRDR = m_model.createIndividual( "http://www.geonames.org/ontology#T.CRDR", Code );
    
    public static final Individual S_CMTY = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMTY", Code );
    
    public static final Individual U_PRVU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PRVU", Code );
    
    public static final Individual P_PPLA = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLA", Code );
    
    public static final Individual T_BAR = m_model.createIndividual( "http://www.geonames.org/ontology#T.BAR", Code );
    
    public static final Individual T_ISLS = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISLS", Code );
    
    public static final Individual R_TRL = m_model.createIndividual( "http://www.geonames.org/ontology#R.TRL", Code );
    
    public static final Individual H_GULF = m_model.createIndividual( "http://www.geonames.org/ontology#H.GULF", Code );
    
    public static final Individual V_HTH = m_model.createIndividual( "http://www.geonames.org/ontology#V.HTH", Code );
    
    public static final Individual U_TERU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TERU", Code );
    
    public static final Individual P_PPLC = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLC", Code );
    
    public static final Individual T_TAL = m_model.createIndividual( "http://www.geonames.org/ontology#T.TAL", Code );
    
    public static final Individual S_ESTB = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTB", Code );
    
    public static final Individual L_NVB = m_model.createIndividual( "http://www.geonames.org/ontology#L.NVB", Code );
    
    public static final Individual T_ISLT = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISLT", Code );
    
    public static final Individual H_OVF = m_model.createIndividual( "http://www.geonames.org/ontology#H.OVF", Code );
    
    public static final Individual S_FT = m_model.createIndividual( "http://www.geonames.org/ontology#S.FT", Code );
    
    public static final Individual H_CUTF = m_model.createIndividual( "http://www.geonames.org/ontology#H.CUTF", Code );
    
    public static final Individual S_COMC = m_model.createIndividual( "http://www.geonames.org/ontology#S.COMC", Code );
    
    public static final Individual T_FAN = m_model.createIndividual( "http://www.geonames.org/ontology#T.FAN", Code );
    
    public static final Individual T_HLLS = m_model.createIndividual( "http://www.geonames.org/ontology#T.HLLS", Code );
    
    public static final Individual U_SDLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SDLU", Code );
    
    public static final Individual P_PPLG = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLG", Code );
    
    public static final Individual L_RESA = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESA", Code );
    
    public static final Individual S_OILR = m_model.createIndividual( "http://www.geonames.org/ontology#S.OILR", Code );
    
    public static final Individual R_TNLRD = m_model.createIndividual( "http://www.geonames.org/ontology#R.TNLRD", Code );
    
    public static final Individual U_ARCU = m_model.createIndividual( "http://www.geonames.org/ontology#U.ARCU", Code );
    
    public static final Individual S_ESTC = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTC", Code );
    
    public static final Individual H_PNDNI = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDNI", Code );
    
    public static final Individual T_SDL = m_model.createIndividual( "http://www.geonames.org/ontology#T.SDL", Code );
    
    public static final Individual H_SHOL = m_model.createIndividual( "http://www.geonames.org/ontology#H.SHOL", Code );
    
    public static final Individual S_SLCE = m_model.createIndividual( "http://www.geonames.org/ontology#S.SLCE", Code );
    
    public static final Individual S_OILQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.OILQ", Code );
    
    public static final Individual T_CONE = m_model.createIndividual( "http://www.geonames.org/ontology#T.CONE", Code );
    
    public static final Individual S_OILT = m_model.createIndividual( "http://www.geonames.org/ontology#S.OILT", Code );
    
    public static final Individual H_DPRG = m_model.createIndividual( "http://www.geonames.org/ontology#H.DPRG", Code );
    
    public static final Individual T_ISLX = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISLX", Code );
    
    public static final Individual T_NTK = m_model.createIndividual( "http://www.geonames.org/ontology#T.NTK", Code );
    
    public static final Individual S_MSSNQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.MSSNQ", Code );
    
    public static final Individual S_MNNI = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNNI", Code );
    
    public static final Individual S_BUR = m_model.createIndividual( "http://www.geonames.org/ontology#S.BUR", Code );
    
    public static final Individual H_LGNS = m_model.createIndividual( "http://www.geonames.org/ontology#H.LGNS", Code );
    
    public static final Individual T_RKS = m_model.createIndividual( "http://www.geonames.org/ontology#T.RKS", Code );
    
    public static final Individual T_HDLD = m_model.createIndividual( "http://www.geonames.org/ontology#T.HDLD", Code );
    
    public static final Individual L_RESF = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESF", Code );
    
    public static final Individual H_SYSI = m_model.createIndividual( "http://www.geonames.org/ontology#H.SYSI", Code );
    
    public static final Individual S_BSTN = m_model.createIndividual( "http://www.geonames.org/ontology#S.BSTN", Code );
    
    public static final Individual S_TOWR = m_model.createIndividual( "http://www.geonames.org/ontology#S.TOWR", Code );
    
    public static final Individual S_SHSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.SHSE", Code );
    
    public static final Individual U_FANU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FANU", Code );
    
    public static final Individual L_RESH = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESH", Code );
    
    public static final Individual U_APNU = m_model.createIndividual( "http://www.geonames.org/ontology#U.APNU", Code );
    
    public static final Individual S_PGDA = m_model.createIndividual( "http://www.geonames.org/ontology#S.PGDA", Code );
    
    public static final Individual S_MAR = m_model.createIndividual( "http://www.geonames.org/ontology#S.MAR", Code );
    
    public static final Individual A_PCL = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCL", Code );
    
    public static final Individual S_PPQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.PPQ", Code );
    
    public static final Individual S_NOV = m_model.createIndividual( "http://www.geonames.org/ontology#S.NOV", Code );
    
    public static final Individual H_AIRS = m_model.createIndividual( "http://www.geonames.org/ontology#H.AIRS", Code );
    
    public static final Individual S_MOLE = m_model.createIndividual( "http://www.geonames.org/ontology#S.MOLE", Code );
    
    public static final Individual S_DARY = m_model.createIndividual( "http://www.geonames.org/ontology#S.DARY", Code );
    
    public static final Individual P_PPLL = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLL", Code );
    
    public static final Individual S_MSQE = m_model.createIndividual( "http://www.geonames.org/ontology#S.MSQE", Code );
    
    public static final Individual T_SPUR = m_model.createIndividual( "http://www.geonames.org/ontology#T.SPUR", Code );
    
    public static final Individual H_CNLB = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLB", Code );
    
    public static final Individual H_ESTY = m_model.createIndividual( "http://www.geonames.org/ontology#H.ESTY", Code );
    
    public static final Individual H_WLL = m_model.createIndividual( "http://www.geonames.org/ontology#H.WLL", Code );
    
    public static final Individual H_RCH = m_model.createIndividual( "http://www.geonames.org/ontology#H.RCH", Code );
    
    public static final Individual H_BAYS = m_model.createIndividual( "http://www.geonames.org/ontology#H.BAYS", Code );
    
    public static final Individual T_DVD = m_model.createIndividual( "http://www.geonames.org/ontology#T.DVD", Code );
    
    public static final Individual S_BDG = m_model.createIndividual( "http://www.geonames.org/ontology#S.BDG", Code );
    
    public static final Individual S_RSTPQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSTPQ", Code );
    
    public static final Individual L_AREA = m_model.createIndividual( "http://www.geonames.org/ontology#L.AREA", Code );
    
    public static final Individual H_CNLA = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLA", Code );
    
    public static final Individual H_STMSB = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMSB", Code );
    
    public static final Individual S_WRCK = m_model.createIndividual( "http://www.geonames.org/ontology#S.WRCK", Code );
    
    public static final Individual H_WTRC = m_model.createIndividual( "http://www.geonames.org/ontology#H.WTRC", Code );
    
    public static final Individual H_RPDS = m_model.createIndividual( "http://www.geonames.org/ontology#H.RPDS", Code );
    
    public static final Individual H_CNLD = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLD", Code );
    
    public static final Individual S_CRRL = m_model.createIndividual( "http://www.geonames.org/ontology#S.CRRL", Code );
    
    public static final Individual P_PPLQ = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLQ", Code );
    
    public static final Individual H_DCK = m_model.createIndividual( "http://www.geonames.org/ontology#H.DCK", Code );
    
    public static final Individual S_ML = m_model.createIndividual( "http://www.geonames.org/ontology#S.ML", Code );
    
    public static final Individual S_PO = m_model.createIndividual( "http://www.geonames.org/ontology#S.PO", Code );
    
    public static final Individual S_DAM = m_model.createIndividual( "http://www.geonames.org/ontology#S.DAM", Code );
    
    public static final Individual P_PPLS = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLS", Code );
    
    public static final Individual L_RESN = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESN", Code );
    
    public static final Individual T_PK = m_model.createIndividual( "http://www.geonames.org/ontology#T.PK", Code );
    
    public static final Individual L_BTL = m_model.createIndividual( "http://www.geonames.org/ontology#L.BTL", Code );
    
    public static final Individual S_MN = m_model.createIndividual( "http://www.geonames.org/ontology#S.MN", Code );
    
    public static final Individual S_ESTO = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTO", Code );
    
    public static final Individual S_MNQR = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNQR", Code );
    
    public static final Individual L_COLF = m_model.createIndividual( "http://www.geonames.org/ontology#L.COLF", Code );
    
    public static final Individual P_PPLR = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLR", Code );
    
    public static final Individual R_TNLRR = m_model.createIndividual( "http://www.geonames.org/ontology#R.TNLRR", Code );
    
    public static final Individual T_MTS = m_model.createIndividual( "http://www.geonames.org/ontology#T.MTS", Code );
    
    public static final Individual S_PP = m_model.createIndividual( "http://www.geonames.org/ontology#S.PP", Code );
    
    public static final Individual L_RESP = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESP", Code );
    
    public static final Individual L_GVL = m_model.createIndividual( "http://www.geonames.org/ontology#L.GVL", Code );
    
    public static final Individual H_BNK = m_model.createIndividual( "http://www.geonames.org/ontology#H.BNK", Code );
    
    public static final Individual T_RKFL = m_model.createIndividual( "http://www.geonames.org/ontology#T.RKFL", Code );
    
    public static final Individual S_ESTR = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTR", Code );
    
    public static final Individual S_MFGPH = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGPH", Code );
    
    public static final Individual L_TRB = m_model.createIndividual( "http://www.geonames.org/ontology#L.TRB", Code );
    
    public static final Individual S_PS = m_model.createIndividual( "http://www.geonames.org/ontology#S.PS", Code );
    
    public static final Individual H_WTRH = m_model.createIndividual( "http://www.geonames.org/ontology#H.WTRH", Code );
    
    public static final Individual S_AIRP = m_model.createIndividual( "http://www.geonames.org/ontology#S.AIRP", Code );
    
    public static final Individual A_LTER = m_model.createIndividual( "http://www.geonames.org/ontology#A.LTER", Code );
    
    public static final Individual S_CMPLA = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPLA", Code );
    
    public static final Individual U_RNGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RNGU", Code );
    
    public static final Individual S_RUIN = m_model.createIndividual( "http://www.geonames.org/ontology#S.RUIN", Code );
    
    public static final Individual T_ASPH = m_model.createIndividual( "http://www.geonames.org/ontology#T.ASPH", Code );
    
    public static final Individual S_CMPL = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPL", Code );
    
    public static final Individual S_ESTT = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTT", Code );
    
    public static final Individual S_SPLY = m_model.createIndividual( "http://www.geonames.org/ontology#S.SPLY", Code );
    
    public static final Individual H_CNLI = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLI", Code );
    
    public static final Individual U_SMSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SMSU", Code );
    
    public static final Individual S_BTYD = m_model.createIndividual( "http://www.geonames.org/ontology#S.BTYD", Code );
    
    public static final Individual H_WADB = m_model.createIndividual( "http://www.geonames.org/ontology#H.WADB", Code );
    
    public static final Individual L_PEAT = m_model.createIndividual( "http://www.geonames.org/ontology#L.PEAT", Code );
    
    public static final Individual S_AIRQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.AIRQ", Code );
    
    public static final Individual S_PSH = m_model.createIndividual( "http://www.geonames.org/ontology#S.PSH", Code );
    
    public static final Individual H_NRWS = m_model.createIndividual( "http://www.geonames.org/ontology#H.NRWS", Code );
    
    public static final Individual S_HSPD = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSPD", Code );
    
    public static final Individual T_VLC = m_model.createIndividual( "http://www.geonames.org/ontology#T.VLC", Code );
    
    public static final Individual H_CNLN = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLN", Code );
    
    public static final Individual L_CONT = m_model.createIndividual( "http://www.geonames.org/ontology#L.CONT", Code );
    
    public static final Individual U_MNDU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MNDU", Code );
    
    public static final Individual S_HSPC = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSPC", Code );
    
    public static final Individual S_ESTX = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTX", Code );
    
    public static final Individual S_CMPQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPQ", Code );
    
    public static final Individual S_RSTN = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSTN", Code );
    
    public static final Individual H_STM = m_model.createIndividual( "http://www.geonames.org/ontology#H.STM", Code );
    
    public static final Individual T_FSR = m_model.createIndividual( "http://www.geonames.org/ontology#T.FSR", Code );
    
    public static final Individual S_CMPO = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPO", Code );
    
    public static final Individual R_CSWY = m_model.createIndividual( "http://www.geonames.org/ontology#R.CSWY", Code );
    
    public static final Individual H_LKSB = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKSB", Code );
    
    public static final Individual S_MSTY = m_model.createIndividual( "http://www.geonames.org/ontology#S.MSTY", Code );
    
    public static final Individual U_RDSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RDSU", Code );
    
    public static final Individual S_RSTP = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSTP", Code );
    
    public static final Individual U_GLYU = m_model.createIndividual( "http://www.geonames.org/ontology#U.GLYU", Code );
    
    public static final Individual S_OBS = m_model.createIndividual( "http://www.geonames.org/ontology#S.OBS", Code );
    
    public static final Individual T_CUET = m_model.createIndividual( "http://www.geonames.org/ontology#T.CUET", Code );
    
    public static final Individual H_CNLQ = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLQ", Code );
    
    public static final Individual S_LTHSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.LTHSE", Code );
    
    public static final Individual S_WALLA = m_model.createIndividual( "http://www.geonames.org/ontology#S.WALLA", Code );
    
    public static final Individual T_CFT = m_model.createIndividual( "http://www.geonames.org/ontology#T.CFT", Code );
    
    public static final Individual S_STDM = m_model.createIndividual( "http://www.geonames.org/ontology#S.STDM", Code );
    
    public static final Individual L_OILF = m_model.createIndividual( "http://www.geonames.org/ontology#L.OILF", Code );
    
    public static final Individual S_MNN = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNN", Code );
    
    public static final Individual H_GLCR = m_model.createIndividual( "http://www.geonames.org/ontology#H.GLCR", Code );
    
    public static final Individual U_EDGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.EDGU", Code );
    
    public static final Individual H_LKSC = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKSC", Code );
    
    public static final Individual L_DEVH = m_model.createIndividual( "http://www.geonames.org/ontology#L.DEVH", Code );
    
    public static final Individual H_WADJ = m_model.createIndividual( "http://www.geonames.org/ontology#H.WADJ", Code );
    
    public static final Individual L_FLD = m_model.createIndividual( "http://www.geonames.org/ontology#L.FLD", Code );
    
    public static final Individual S_ATHF = m_model.createIndividual( "http://www.geonames.org/ontology#S.ATHF", Code );
    
    public static final Individual H_SEA = m_model.createIndividual( "http://www.geonames.org/ontology#H.SEA", Code );
    
    public static final Individual S_MNQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNQ", Code );
    
    public static final Individual U_SCSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SCSU", Code );
    
    public static final Individual S_HSEC = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSEC", Code );
    
    public static final Individual S_TNKD = m_model.createIndividual( "http://www.geonames.org/ontology#S.TNKD", Code );
    
    public static final Individual U_BNKU = m_model.createIndividual( "http://www.geonames.org/ontology#U.BNKU", Code );
    
    public static final Individual S_LEPC = m_model.createIndividual( "http://www.geonames.org/ontology#S.LEPC", Code );
    
    public static final Individual S_BDGQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.BDGQ", Code );
    
    public static final Individual S_RECG = m_model.createIndividual( "http://www.geonames.org/ontology#S.RECG", Code );
    
    public static final Individual R_ST = m_model.createIndividual( "http://www.geonames.org/ontology#R.ST", Code );
    
    public static final Individual H_DOMG = m_model.createIndividual( "http://www.geonames.org/ontology#H.DOMG", Code );
    
    public static final Individual U_RFSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RFSU", Code );
    
    public static final Individual H_DTCHM = m_model.createIndividual( "http://www.geonames.org/ontology#H.DTCHM", Code );
    
    public static final Individual R_TNL = m_model.createIndividual( "http://www.geonames.org/ontology#R.TNL", Code );
    
    public static final Individual S_RLGR = m_model.createIndividual( "http://www.geonames.org/ontology#S.RLGR", Code );
    
    public static final Individual H_LKSI = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKSI", Code );
    
    public static final Individual T_DSRT = m_model.createIndividual( "http://www.geonames.org/ontology#T.DSRT", Code );
    
    public static final Individual H_WADM = m_model.createIndividual( "http://www.geonames.org/ontology#H.WADM", Code );
    
    public static final Individual S_RSRT = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSRT", Code );
    
    public static final Individual U_RISU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RISU", Code );
    
    public static final Individual U_BSNU = m_model.createIndividual( "http://www.geonames.org/ontology#U.BSNU", Code );
    
    public static final Individual U_SHSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SHSU", Code );
    
    public static final Individual S_OBSR = m_model.createIndividual( "http://www.geonames.org/ontology#S.OBSR", Code );
    
    public static final Individual H_MGV = m_model.createIndividual( "http://www.geonames.org/ontology#H.MGV", Code );
    
    public static final Individual S_MKT = m_model.createIndividual( "http://www.geonames.org/ontology#S.MKT", Code );
    
    /** <p>parks,area, ...</p> */
    public static final Individual L = m_model.createIndividual( "http://www.geonames.org/ontology#L", Class );
    
    public static final Individual S_CSTL = m_model.createIndividual( "http://www.geonames.org/ontology#S.CSTL", Code );
    
    public static final Individual L_SNOW = m_model.createIndividual( "http://www.geonames.org/ontology#L.SNOW", Code );
    
    public static final Individual S_VETF = m_model.createIndividual( "http://www.geonames.org/ontology#S.VETF", Code );
    
    public static final Individual T_INTF = m_model.createIndividual( "http://www.geonames.org/ontology#T.INTF", Code );
    
    public static final Individual T_MRN = m_model.createIndividual( "http://www.geonames.org/ontology#T.MRN", Code );
    
    public static final Individual H_LKSN = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKSN", Code );
    
    public static final Individual A_ADM1 = m_model.createIndividual( "http://www.geonames.org/ontology#A.ADM1", Code );
    
    public static final Individual S_PRKHQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.PRKHQ", Code );
    
    public static final Individual V_OCH = m_model.createIndividual( "http://www.geonames.org/ontology#V.OCH", Code );
    
    public static final Individual A_ADM3 = m_model.createIndividual( "http://www.geonames.org/ontology#A.ADM3", Code );
    
    public static final Individual S_MFGQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGQ", Code );
    
    public static final Individual H_LKNI = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKNI", Code );
    
    public static final Individual S_CSTM = m_model.createIndividual( "http://www.geonames.org/ontology#S.CSTM", Code );
    
    /** <p>city, village,...</p> */
    public static final Individual P = m_model.createIndividual( "http://www.geonames.org/ontology#P", Class );
    
    public static final Individual V_GRVC = m_model.createIndividual( "http://www.geonames.org/ontology#V.GRVC", Code );
    
    public static final Individual L_OAS = m_model.createIndividual( "http://www.geonames.org/ontology#L.OAS", Code );
    
    public static final Individual A_TERR = m_model.createIndividual( "http://www.geonames.org/ontology#A.TERR", Code );
    
    public static final Individual S_WEIR = m_model.createIndividual( "http://www.geonames.org/ontology#S.WEIR", Code );
    
    public static final Individual U_RFU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RFU", Code );
    
    public static final Individual H_WADS = m_model.createIndividual( "http://www.geonames.org/ontology#H.WADS", Code );
    
    public static final Individual A_ADM2 = m_model.createIndividual( "http://www.geonames.org/ontology#A.ADM2", Code );
    
    public static final Individual S_RECR = m_model.createIndividual( "http://www.geonames.org/ontology#S.RECR", Code );
    
    public static final Individual U_HOLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.HOLU", Code );
    
    public static final Individual L_PRK = m_model.createIndividual( "http://www.geonames.org/ontology#L.PRK", Code );
    
    public static final Individual S_SCHA = m_model.createIndividual( "http://www.geonames.org/ontology#S.SCHA", Code );
    
    public static final Individual R_CSWYQ = m_model.createIndividual( "http://www.geonames.org/ontology#R.CSWYQ", Code );
    
    public static final Individual A_ADM4 = m_model.createIndividual( "http://www.geonames.org/ontology#A.ADM4", Code );
    
    public static final Individual T_ISTH = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISTH", Code );
    
    public static final Individual H_LKSNI = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKSNI", Code );
    
    public static final Individual L_CTRB = m_model.createIndividual( "http://www.geonames.org/ontology#L.CTRB", Code );
    
    public static final Individual S_ADMF = m_model.createIndividual( "http://www.geonames.org/ontology#S.ADMF", Code );
    
    public static final Individual T_HMCK = m_model.createIndividual( "http://www.geonames.org/ontology#T.HMCK", Code );
    
    /** <p>spot, building, farm, ...</p> */
    public static final Individual S = m_model.createIndividual( "http://www.geonames.org/ontology#S", Class );
    
    public static final Individual T_GAP = m_model.createIndividual( "http://www.geonames.org/ontology#T.GAP", Code );
    
    public static final Individual S_MLWND = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLWND", Code );
    
    public static final Individual H_BAY = m_model.createIndividual( "http://www.geonames.org/ontology#H.BAY", Code );
    
    /** <p>mountain, hill, rock, ...</p> */
    public static final Individual T = m_model.createIndividual( "http://www.geonames.org/ontology#T", Class );
    
    public static final Individual U_HLLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.HLLU", Code );
    
    public static final Individual H_WADX = m_model.createIndividual( "http://www.geonames.org/ontology#H.WADX", Code );
    
    public static final Individual P_STLMT = m_model.createIndividual( "http://www.geonames.org/ontology#P.STLMT", Code );
    
    public static final Individual S_MNPL = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNPL", Code );
    
    public static final Individual U_LEVU = m_model.createIndividual( "http://www.geonames.org/ontology#U.LEVU", Code );
    
    public static final Individual S_SCHC = m_model.createIndividual( "http://www.geonames.org/ontology#S.SCHC", Code );
    
    public static final Individual U_FRZU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FRZU", Code );
    
    public static final Individual H_HBRX = m_model.createIndividual( "http://www.geonames.org/ontology#H.HBRX", Code );
    
    public static final Individual S_MNSN = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNSN", Code );
    
    /** <p>road, railroad, ...</p> */
    public static final Individual R = m_model.createIndividual( "http://www.geonames.org/ontology#R", Class );
    
    public static final Individual H_FLLS = m_model.createIndividual( "http://www.geonames.org/ontology#H.FLLS", Code );
    
    public static final Individual S_ITTR = m_model.createIndividual( "http://www.geonames.org/ontology#S.ITTR", Code );
    
    public static final Individual H_CNLSB = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLSB", Code );
    
    public static final Individual S_CTRS = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRS", Code );
    
    public static final Individual H_CHNN = m_model.createIndividual( "http://www.geonames.org/ontology#H.CHNN", Code );
    
    public static final Individual A_PCLD = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCLD", Code );
    
    public static final Individual U_DEPU = m_model.createIndividual( "http://www.geonames.org/ontology#U.DEPU", Code );
    
    public static final Individual H_CHNM = m_model.createIndividual( "http://www.geonames.org/ontology#H.CHNM", Code );
    
    public static final Individual S_SQR = m_model.createIndividual( "http://www.geonames.org/ontology#S.SQR", Code );
    
    public static final Individual S_MNFE = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNFE", Code );
    
    public static final Individual U_SILU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SILU", Code );
    
    public static final Individual A_ZN = m_model.createIndividual( "http://www.geonames.org/ontology#A.ZN", Code );
    
    public static final Individual H_PND = m_model.createIndividual( "http://www.geonames.org/ontology#H.PND", Code );
    
    public static final Individual S_DPOF = m_model.createIndividual( "http://www.geonames.org/ontology#S.DPOF", Code );
    
    public static final Individual T_SINK = m_model.createIndividual( "http://www.geonames.org/ontology#T.SINK", Code );
    
    public static final Individual U_PLNU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PLNU", Code );
    
    public static final Individual T_BDLD = m_model.createIndividual( "http://www.geonames.org/ontology#T.BDLD", Code );
    
    public static final Individual A_PCLF = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCLF", Code );
    
    /** <p>undersea</p> */
    public static final Individual U = m_model.createIndividual( "http://www.geonames.org/ontology#U", Class );
    
    public static final Individual S_ASYL = m_model.createIndividual( "http://www.geonames.org/ontology#S.ASYL", Code );
    
    public static final Individual T_CLDA = m_model.createIndividual( "http://www.geonames.org/ontology#T.CLDA", Code );
    
    public static final Individual L_LCTY = m_model.createIndividual( "http://www.geonames.org/ontology#L.LCTY", Code );
    
    public static final Individual H_STMI = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMI", Code );
    
    /** <p>forest, heath, ...</p> */
    public static final Individual V = m_model.createIndividual( "http://www.geonames.org/ontology#V", Class );
    
    public static final Individual S_BCN = m_model.createIndividual( "http://www.geonames.org/ontology#S.BCN", Code );
    
    public static final Individual H_DTCHD = m_model.createIndividual( "http://www.geonames.org/ontology#H.DTCHD", Code );
    
    public static final Individual S_MSSN = m_model.createIndividual( "http://www.geonames.org/ontology#S.MSSN", Code );
    
    public static final Individual H_STMH = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMH", Code );
    
    public static final Individual T_ISLF = m_model.createIndividual( "http://www.geonames.org/ontology#T.ISLF", Code );
    
    public static final Individual T_PEN = m_model.createIndividual( "http://www.geonames.org/ontology#T.PEN", Code );
    
    public static final Individual L_MVA = m_model.createIndividual( "http://www.geonames.org/ontology#L.MVA", Code );
    
    public static final Individual S_GRVE = m_model.createIndividual( "http://www.geonames.org/ontology#S.GRVE", Code );
    
    public static final Individual R_RTE = m_model.createIndividual( "http://www.geonames.org/ontology#R.RTE", Code );
    
    public static final Individual S_MLSW = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLSW", Code );
    
    public static final Individual H_WAD = m_model.createIndividual( "http://www.geonames.org/ontology#H.WAD", Code );
    
    public static final Individual V_GRVO = m_model.createIndividual( "http://www.geonames.org/ontology#V.GRVO", Code );
    
    public static final Individual S_STNM = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNM", Code );
    
    public static final Individual L_PRT = m_model.createIndividual( "http://www.geonames.org/ontology#L.PRT", Code );
    
    public static final Individual H_DTCHI = m_model.createIndividual( "http://www.geonames.org/ontology#H.DTCHI", Code );
    
    public static final Individual H_CNL = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNL", Code );
    
    public static final Individual H_POOLI = m_model.createIndividual( "http://www.geonames.org/ontology#H.POOLI", Code );
    
    public static final Individual S_ARCH = m_model.createIndividual( "http://www.geonames.org/ontology#S.ARCH", Code );
    
    public static final Individual H_COVE = m_model.createIndividual( "http://www.geonames.org/ontology#H.COVE", Code );
    
    public static final Individual S_MNMT = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNMT", Code );
    
    public static final Individual A_PCLI = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCLI", Code );
    
    public static final Individual S_QUAY = m_model.createIndividual( "http://www.geonames.org/ontology#S.QUAY", Code );
    
    public static final Individual U_MOTU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MOTU", Code );
    
    public static final Individual H_STMM = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMM", Code );
    
    public static final Individual S_HUTS = m_model.createIndividual( "http://www.geonames.org/ontology#S.HUTS", Code );
    
    public static final Individual S_SCHN = m_model.createIndividual( "http://www.geonames.org/ontology#S.SCHN", Code );
    
    public static final Individual U_PLFU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PLFU", Code );
    
    public static final Individual V_GRVP = m_model.createIndividual( "http://www.geonames.org/ontology#V.GRVP", Code );
    
    public static final Individual U_BDLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.BDLU", Code );
    
    public static final Individual A_ZNB = m_model.createIndividual( "http://www.geonames.org/ontology#A.ZNB", Code );
    
    public static final Individual S_RKRY = m_model.createIndividual( "http://www.geonames.org/ontology#S.RKRY", Code );
    
    public static final Individual S_SCHM = m_model.createIndividual( "http://www.geonames.org/ontology#S.SCHM", Code );
    
    public static final Individual A_ADMD = m_model.createIndividual( "http://www.geonames.org/ontology#A.ADMD", Code );
    
    public static final Individual H_LKX = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKX", Code );
    
    /** <p>country, state, region ...</p> */
    public static final Individual A = m_model.createIndividual( "http://www.geonames.org/ontology#A", Class );
    
    public static final Individual T_DUNE = m_model.createIndividual( "http://www.geonames.org/ontology#T.DUNE", Code );
    
    public static final Individual H_FLTM = m_model.createIndividual( "http://www.geonames.org/ontology#H.FLTM", Code );
    
    public static final Individual T_SCRP = m_model.createIndividual( "http://www.geonames.org/ontology#T.SCRP", Code );
    
    public static final Individual T_TRGD = m_model.createIndividual( "http://www.geonames.org/ontology#T.TRGD", Code );
    
    public static final Individual S_STNS = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNS", Code );
    
    public static final Individual H_RFC = m_model.createIndividual( "http://www.geonames.org/ontology#H.RFC", Code );
    
    public static final Individual H_SD = m_model.createIndividual( "http://www.geonames.org/ontology#H.SD", Code );
    
    public static final Individual H_STMQ = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMQ", Code );
    
    public static final Individual L_REP = m_model.createIndividual( "http://www.geonames.org/ontology#L.REP", Code );
    
    public static final Individual S_STNR = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNR", Code );
    
    /** <p>stream, lake, ...</p> */
    public static final Individual H = m_model.createIndividual( "http://www.geonames.org/ontology#H", Class );
    
    public static final Individual T_UPLD = m_model.createIndividual( "http://www.geonames.org/ontology#T.UPLD", Code );
    
    public static final Individual H_CNFL = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNFL", Code );
    
    public static final Individual S_MFGLM = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGLM", Code );
    
    public static final Individual L_AGRC = m_model.createIndividual( "http://www.geonames.org/ontology#L.AGRC", Code );
    
    public static final Individual L_RESV = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESV", Code );
    
    public static final Individual H_STMS = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMS", Code );
    
    public static final Individual V_VIN = m_model.createIndividual( "http://www.geonames.org/ontology#V.VIN", Code );
    
    public static final Individual L_RES = m_model.createIndividual( "http://www.geonames.org/ontology#L.RES", Code );
    
    public static final Individual T_CAPE = m_model.createIndividual( "http://www.geonames.org/ontology#T.CAPE", Code );
    
    public static final Individual U_FURU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FURU", Code );
    
    public static final Individual S_ASTR = m_model.createIndividual( "http://www.geonames.org/ontology#S.ASTR", Code );
    
    public static final Individual A_PCLS = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCLS", Code );
    
    public static final Individual L_MNA = m_model.createIndividual( "http://www.geonames.org/ontology#L.MNA", Code );
    
    public static final Individual S_STNW = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNW", Code );
    
    public static final Individual S_FRMQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.FRMQ", Code );
    
    public static final Individual T_MND = m_model.createIndividual( "http://www.geonames.org/ontology#T.MND", Code );
    
    public static final Individual S_PRN = m_model.createIndividual( "http://www.geonames.org/ontology#S.PRN", Code );
    
    public static final Individual S_LDNG = m_model.createIndividual( "http://www.geonames.org/ontology#S.LDNG", Code );
    
    public static final Individual H_FLTT = m_model.createIndividual( "http://www.geonames.org/ontology#H.FLTT", Code );
    
    public static final Individual L_RESW = m_model.createIndividual( "http://www.geonames.org/ontology#L.RESW", Code );
    
    public static final Individual S_FRMT = m_model.createIndividual( "http://www.geonames.org/ontology#S.FRMT", Code );
    
    public static final Individual S_PMPW = m_model.createIndividual( "http://www.geonames.org/ontology#S.PMPW", Code );
    
    public static final Individual S_SPA = m_model.createIndividual( "http://www.geonames.org/ontology#S.SPA", Code );
    
    public static final Individual T_CNYN = m_model.createIndividual( "http://www.geonames.org/ontology#T.CNYN", Code );
    
    public static final Individual S_UNIV = m_model.createIndividual( "http://www.geonames.org/ontology#S.UNIV", Code );
    
    public static final Individual H_STMX = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMX", Code );
    
    public static final Individual S_FRMS = m_model.createIndividual( "http://www.geonames.org/ontology#S.FRMS", Code );
    
    public static final Individual H_MOOR = m_model.createIndividual( "http://www.geonames.org/ontology#H.MOOR", Code );
    
    public static final Individual S_CARN = m_model.createIndividual( "http://www.geonames.org/ontology#S.CARN", Code );
    
    public static final Individual T_MT = m_model.createIndividual( "http://www.geonames.org/ontology#T.MT", Code );
    
    public static final Individual R_RR = m_model.createIndividual( "http://www.geonames.org/ontology#R.RR", Code );
    
    public static final Individual T_HMDA = m_model.createIndividual( "http://www.geonames.org/ontology#T.HMDA", Code );
    
    public static final Individual H_MRSH = m_model.createIndividual( "http://www.geonames.org/ontology#H.MRSH", Code );
    
    public static final Individual S_MNDT = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNDT", Code );
    
    public static final Individual H_CRNT = m_model.createIndividual( "http://www.geonames.org/ontology#H.CRNT", Code );
    
    public static final Individual R_RRQ = m_model.createIndividual( "http://www.geonames.org/ontology#R.RRQ", Code );
    
    public static final Individual U_HLSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.HLSU", Code );
    
    public static final Individual S_TRIG = m_model.createIndividual( "http://www.geonames.org/ontology#S.TRIG", Code );
    
    public static final Individual H_CRKT = m_model.createIndividual( "http://www.geonames.org/ontology#H.CRKT", Code );
    
    public static final Individual H_LBED = m_model.createIndividual( "http://www.geonames.org/ontology#H.LBED", Code );
    
    public static final Individual H_INLTQ = m_model.createIndividual( "http://www.geonames.org/ontology#H.INLTQ", Code );
    
    public static final Individual T_PLNX = m_model.createIndividual( "http://www.geonames.org/ontology#T.PLNX", Code );
    
    public static final Individual H_SWMP = m_model.createIndividual( "http://www.geonames.org/ontology#H.SWMP", Code );
    
    public static final Individual U_CNYU = m_model.createIndividual( "http://www.geonames.org/ontology#U.CNYU", Code );
    
    public static final Individual S_AIRB = m_model.createIndividual( "http://www.geonames.org/ontology#S.AIRB", Code );
    
    public static final Individual H_CNLX = m_model.createIndividual( "http://www.geonames.org/ontology#H.CNLX", Code );
    
    public static final Individual S_MNAU = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNAU", Code );
    
    public static final Individual T_PENX = m_model.createIndividual( "http://www.geonames.org/ontology#T.PENX", Code );
    
    public static final Individual U_SHLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SHLU", Code );
    
    public static final Individual V_MDW = m_model.createIndividual( "http://www.geonames.org/ontology#V.MDW", Code );
    
    public static final Individual R_PRMN = m_model.createIndividual( "http://www.geonames.org/ontology#R.PRMN", Code );
    
    public static final Individual S_USGE = m_model.createIndividual( "http://www.geonames.org/ontology#S.USGE", Code );
    
    public static final Individual S_MFGSG = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGSG", Code );
    
    public static final Individual S_OILW = m_model.createIndividual( "http://www.geonames.org/ontology#S.OILW", Code );
    
    public static final Individual S_HUT = m_model.createIndividual( "http://www.geonames.org/ontology#S.HUT", Code );
    
    public static final Individual S_AIRF = m_model.createIndividual( "http://www.geonames.org/ontology#S.AIRF", Code );
    
    public static final Individual S_HERM = m_model.createIndividual( "http://www.geonames.org/ontology#S.HERM", Code );
    
    public static final Individual H_SBKH = m_model.createIndividual( "http://www.geonames.org/ontology#H.SBKH", Code );
    
    public static final Individual T_VALS = m_model.createIndividual( "http://www.geonames.org/ontology#T.VALS", Code );
    
    public static final Individual U_RMPU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RMPU", Code );
    
    public static final Individual T_PTS = m_model.createIndividual( "http://www.geonames.org/ontology#T.PTS", Code );
    
    public static final Individual S_AIRH = m_model.createIndividual( "http://www.geonames.org/ontology#S.AIRH", Code );
    
    public static final Individual H_INLT = m_model.createIndividual( "http://www.geonames.org/ontology#H.INLT", Code );
    
    public static final Individual H_BGHT = m_model.createIndividual( "http://www.geonames.org/ontology#H.BGHT", Code );
    
    public static final Individual S_OBPT = m_model.createIndividual( "http://www.geonames.org/ontology#S.OBPT", Code );
    
    public static final Individual H_RDST = m_model.createIndividual( "http://www.geonames.org/ontology#H.RDST", Code );
    
    public static final Individual V_GRVPN = m_model.createIndividual( "http://www.geonames.org/ontology#V.GRVPN", Code );
    
    public static final Individual U_ARRU = m_model.createIndividual( "http://www.geonames.org/ontology#U.ARRU", Code );
    
    public static final Individual U_PNLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PNLU", Code );
    
    public static final Individual S_PRKGT = m_model.createIndividual( "http://www.geonames.org/ontology#S.PRKGT", Code );
    
    public static final Individual H_RFX = m_model.createIndividual( "http://www.geonames.org/ontology#H.RFX", Code );
    
    public static final Individual T_VALX = m_model.createIndividual( "http://www.geonames.org/ontology#T.VALX", Code );
    
    public static final Individual R_TNLN = m_model.createIndividual( "http://www.geonames.org/ontology#R.TNLN", Code );
    
    public static final Individual S_CMPRF = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPRF", Code );
    
    public static final Individual S_RNCH = m_model.createIndividual( "http://www.geonames.org/ontology#S.RNCH", Code );
    
    public static final Individual S_DCKD = m_model.createIndividual( "http://www.geonames.org/ontology#S.DCKD", Code );
    
    public static final Individual T_ERG = m_model.createIndividual( "http://www.geonames.org/ontology#T.ERG", Code );
    
    public static final Individual S_RSTNQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSTNQ", Code );
    
    public static final Individual H_SPNG = m_model.createIndividual( "http://www.geonames.org/ontology#H.SPNG", Code );
    
    public static final Individual S_SHRN = m_model.createIndividual( "http://www.geonames.org/ontology#S.SHRN", Code );
    
    public static final Individual V_FRST = m_model.createIndividual( "http://www.geonames.org/ontology#V.FRST", Code );
    
    public static final Individual S_MNC = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNC", Code );
    
    public static final Individual L_LAND = m_model.createIndividual( "http://www.geonames.org/ontology#L.LAND", Code );
    
    public static final Individual R_TNLS = m_model.createIndividual( "http://www.geonames.org/ontology#R.TNLS", Code );
    
    public static final Individual P_PPL = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPL", Code );
    
    public static final Individual U_SLPU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SLPU", Code );
    
    public static final Individual A_PRSH = m_model.createIndividual( "http://www.geonames.org/ontology#A.PRSH", Code );
    
    public static final Individual H_TNLC = m_model.createIndividual( "http://www.geonames.org/ontology#H.TNLC", Code );
    
    public static final Individual U_GAPU = m_model.createIndividual( "http://www.geonames.org/ontology#U.GAPU", Code );
    
    public static final Individual H_MRSHN = m_model.createIndividual( "http://www.geonames.org/ontology#H.MRSHN", Code );
    
    public static final Individual T_SHOR = m_model.createIndividual( "http://www.geonames.org/ontology#T.SHOR", Code );
    
    public static final Individual S_SCH = m_model.createIndividual( "http://www.geonames.org/ontology#S.SCH", Code );
    
    public static final Individual S_PYR = m_model.createIndividual( "http://www.geonames.org/ontology#S.PYR", Code );
    
    public static final Individual S_EST = m_model.createIndividual( "http://www.geonames.org/ontology#S.EST", Code );
    
    public static final Individual H_LGN = m_model.createIndividual( "http://www.geonames.org/ontology#H.LGN", Code );
    
    public static final Individual A_PCLIX = m_model.createIndividual( "http://www.geonames.org/ontology#A.PCLIX", Code );
    
    public static final Individual L_RNGA = m_model.createIndividual( "http://www.geonames.org/ontology#L.RNGA", Code );
    
    public static final Individual H_RSVI = m_model.createIndividual( "http://www.geonames.org/ontology#H.RSVI", Code );
    
    public static final Individual T_PAN = m_model.createIndividual( "http://www.geonames.org/ontology#T.PAN", Code );
    
    public static final Individual L_CNS = m_model.createIndividual( "http://www.geonames.org/ontology#L.CNS", Code );
    
    public static final Individual S_ESTSG = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTSG", Code );
    
    public static final Individual T_TRR = m_model.createIndividual( "http://www.geonames.org/ontology#T.TRR", Code );
    
    public static final Individual S_CAVE = m_model.createIndividual( "http://www.geonames.org/ontology#S.CAVE", Code );
    
    public static final Individual T_PROM = m_model.createIndividual( "http://www.geonames.org/ontology#T.PROM", Code );
    
    public static final Individual U_TRNU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TRNU", Code );
    
    public static final Individual T_BUTE = m_model.createIndividual( "http://www.geonames.org/ontology#T.BUTE", Code );
    
    public static final Individual T_MESA = m_model.createIndividual( "http://www.geonames.org/ontology#T.MESA", Code );
    
    public static final Individual S_FCL = m_model.createIndividual( "http://www.geonames.org/ontology#S.FCL", Code );
    
    public static final Individual V_BUSH = m_model.createIndividual( "http://www.geonames.org/ontology#V.BUSH", Code );
    
    public static final Individual S_PRNJ = m_model.createIndividual( "http://www.geonames.org/ontology#S.PRNJ", Code );
    
    public static final Individual U_ESCU = m_model.createIndividual( "http://www.geonames.org/ontology#U.ESCU", Code );
    
    public static final Individual S_PSTP = m_model.createIndividual( "http://www.geonames.org/ontology#S.PSTP", Code );
    
    public static final Individual L_RGN = m_model.createIndividual( "http://www.geonames.org/ontology#L.RGN", Code );
    
    public static final Individual V_TREE = m_model.createIndividual( "http://www.geonames.org/ontology#V.TREE", Code );
    
    public static final Individual H_PNDSI = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDSI", Code );
    
    public static final Individual H_CHN = m_model.createIndividual( "http://www.geonames.org/ontology#H.CHN", Code );
    
    public static final Individual S_TMPL = m_model.createIndividual( "http://www.geonames.org/ontology#S.TMPL", Code );
    
    public static final Individual H_RVN = m_model.createIndividual( "http://www.geonames.org/ontology#H.RVN", Code );
    
    public static final Individual S_CMPMN = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMPMN", Code );
    
    public static final Individual S_CTRA = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRA", Code );
    
    public static final Individual T_NTKS = m_model.createIndividual( "http://www.geonames.org/ontology#T.NTKS", Code );
    
    public static final Individual H_SPNT = m_model.createIndividual( "http://www.geonames.org/ontology#H.SPNT", Code );
    
    public static final Individual H_POOL = m_model.createIndividual( "http://www.geonames.org/ontology#H.POOL", Code );
    
    public static final Individual T_SLID = m_model.createIndividual( "http://www.geonames.org/ontology#T.SLID", Code );
    
    public static final Individual U_TMTU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TMTU", Code );
    
    public static final Individual H_SPNS = m_model.createIndividual( "http://www.geonames.org/ontology#H.SPNS", Code );
    
    public static final Individual S_ESTSL = m_model.createIndividual( "http://www.geonames.org/ontology#S.ESTSL", Code );
    
    public static final Individual H_PNDSN = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDSN", Code );
    
    public static final Individual T_SLP = m_model.createIndividual( "http://www.geonames.org/ontology#T.SLP", Code );
    
    public static final Individual S_BRKS = m_model.createIndividual( "http://www.geonames.org/ontology#S.BRKS", Code );
    
    public static final Individual S_PRNQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.PRNQ", Code );
    
    public static final Individual H_RSVT = m_model.createIndividual( "http://www.geonames.org/ontology#H.RSVT", Code );
    
    public static final Individual S_STBL = m_model.createIndividual( "http://www.geonames.org/ontology#S.STBL", Code );
    
    public static final Individual H_FLLSX = m_model.createIndividual( "http://www.geonames.org/ontology#H.FLLSX", Code );
    
    public static final Individual S_RLG = m_model.createIndividual( "http://www.geonames.org/ontology#S.RLG", Code );
    
    public static final Individual U_BNCU = m_model.createIndividual( "http://www.geonames.org/ontology#U.BNCU", Code );
    
    public static final Individual V_FRSTF = m_model.createIndividual( "http://www.geonames.org/ontology#V.FRSTF", Code );
    
    public static final Individual T_REG = m_model.createIndividual( "http://www.geonames.org/ontology#T.REG", Code );
    
    public static final Individual S_GDN = m_model.createIndividual( "http://www.geonames.org/ontology#S.GDN", Code );
    
    public static final Individual S_BRKW = m_model.createIndividual( "http://www.geonames.org/ontology#S.BRKW", Code );
    
    public static final Individual H_LKC = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKC", Code );
    
    public static final Individual S_TMB = m_model.createIndividual( "http://www.geonames.org/ontology#S.TMB", Code );
    
    public static final Individual R_RDA = m_model.createIndividual( "http://www.geonames.org/ontology#R.RDA", Code );
    
    public static final Individual V_GRSLD = m_model.createIndividual( "http://www.geonames.org/ontology#V.GRSLD", Code );
    
    public static final Individual U_KNSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.KNSU", Code );
    
    public static final Individual T_LAVA = m_model.createIndividual( "http://www.geonames.org/ontology#T.LAVA", Code );
    
    public static final Individual T_BNCH = m_model.createIndividual( "http://www.geonames.org/ontology#T.BNCH", Code );
    
    public static final Individual S_CTRF = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRF", Code );
    
    public static final Individual S_MNCR = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNCR", Code );
    
    public static final Individual T_SAND = m_model.createIndividual( "http://www.geonames.org/ontology#T.SAND", Code );
    
    public static final Individual S_DCKY = m_model.createIndividual( "http://www.geonames.org/ontology#S.DCKY", Code );
    
    public static final Individual S_JTY = m_model.createIndividual( "http://www.geonames.org/ontology#S.JTY", Code );
    
    public static final Individual S_MNPB = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNPB", Code );
    
    public static final Individual H_LK = m_model.createIndividual( "http://www.geonames.org/ontology#H.LK", Code );
    
    public static final Individual S_MLSG = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLSG", Code );
    
    public static final Individual S_HTL = m_model.createIndividual( "http://www.geonames.org/ontology#S.HTL", Code );
    
    public static final Individual S_FY = m_model.createIndividual( "http://www.geonames.org/ontology#S.FY", Code );
    
    public static final Individual U_SMU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SMU", Code );
    
    public static final Individual U_BKSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.BKSU", Code );
    
    public static final Individual U_SCNU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SCNU", Code );
    
    public static final Individual S_FNDY = m_model.createIndividual( "http://www.geonames.org/ontology#S.FNDY", Code );
    
    public static final Individual R_RDB = m_model.createIndividual( "http://www.geonames.org/ontology#R.RDB", Code );
    
    public static final Individual S_GATE = m_model.createIndividual( "http://www.geonames.org/ontology#S.GATE", Code );
    
    public static final Individual U_VLSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.VLSU", Code );
    
    public static final Individual U_FLTU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FLTU", Code );
    
    public static final Individual S_WALL = m_model.createIndividual( "http://www.geonames.org/ontology#S.WALL", Code );
    
    public static final Individual S_MNCU = m_model.createIndividual( "http://www.geonames.org/ontology#S.MNCU", Code );
    
    public static final Individual H_LKI = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKI", Code );
    
    public static final Individual T_GRGE = m_model.createIndividual( "http://www.geonames.org/ontology#T.GRGE", Code );
    
    public static final Individual U_CNSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.CNSU", Code );
    
    public static final Individual S_CTRM = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRM", Code );
    
    public static final Individual S_CTHSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTHSE", Code );
    
    public static final Individual H_STMA = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMA", Code );
    
    public static final Individual H_LGNX = m_model.createIndividual( "http://www.geonames.org/ontology#H.LGNX", Code );
    
    public static final Individual S_MFGCU = m_model.createIndividual( "http://www.geonames.org/ontology#S.MFGCU", Code );
    
    public static final Individual L_BSND = m_model.createIndividual( "http://www.geonames.org/ontology#L.BSND", Code );
    
    public static final Individual S_STNC = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNC", Code );
    
    public static final Individual H_WLLQ = m_model.createIndividual( "http://www.geonames.org/ontology#H.WLLQ", Code );
    
    public static final Individual H_LKOI = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKOI", Code );
    
    public static final Individual U_PKU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PKU", Code );
    
    public static final Individual H_STMC = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMC", Code );
    
    public static final Individual S_STNB = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNB", Code );
    
    public static final Individual S_CTRR = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRR", Code );
    
    public static final Individual T_DLTA = m_model.createIndividual( "http://www.geonames.org/ontology#T.DLTA", Code );
    
    public static final Individual H_RDGG = m_model.createIndividual( "http://www.geonames.org/ontology#H.RDGG", Code );
    
    public static final Individual H_STMB = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMB", Code );
    
    public static final Individual H_CHNL = m_model.createIndividual( "http://www.geonames.org/ontology#H.CHNL", Code );
    
    public static final Individual S_STNE = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNE", Code );
    
    public static final Individual H_WLLS = m_model.createIndividual( "http://www.geonames.org/ontology#H.WLLS", Code );
    
    public static final Individual S_PKLT = m_model.createIndividual( "http://www.geonames.org/ontology#S.PKLT", Code );
    
    public static final Individual T_RK = m_model.createIndividual( "http://www.geonames.org/ontology#T.RK", Code );
    
    public static final Individual S_FRM = m_model.createIndividual( "http://www.geonames.org/ontology#S.FRM", Code );
    
    public static final Individual H_STMIX = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMIX", Code );
    
    public static final Individual H_LKO = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKO", Code );
    
    public static final Individual U_SHFU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SHFU", Code );
    
    public static final Individual T_LEV = m_model.createIndividual( "http://www.geonames.org/ontology#T.LEV", Code );
    
    public static final Individual S_RSD = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSD", Code );
    
    public static final Individual S_DAMSB = m_model.createIndividual( "http://www.geonames.org/ontology#S.DAMSB", Code );
    
    public static final Individual H_STMD = m_model.createIndividual( "http://www.geonames.org/ontology#H.STMD", Code );
    
    public static final Individual H_BNKR = m_model.createIndividual( "http://www.geonames.org/ontology#H.BNKR", Code );
    
    public static final Individual H_LKN = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKN", Code );
    
    public static final Individual P_PPLX = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLX", Code );
    
    public static final Individual T_NKM = m_model.createIndividual( "http://www.geonames.org/ontology#T.NKM", Code );
    
    public static final Individual S_STNF = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNF", Code );
    
    public static final Individual S_STNI = m_model.createIndividual( "http://www.geonames.org/ontology#S.STNI", Code );
    
    public static final Individual P_PPLW = m_model.createIndividual( "http://www.geonames.org/ontology#P.PPLW", Code );
    
    public static final Individual L_RGNE = m_model.createIndividual( "http://www.geonames.org/ontology#L.RGNE", Code );
    
    public static final Individual H_WTLD = m_model.createIndividual( "http://www.geonames.org/ontology#H.WTLD", Code );
    
    public static final Individual S_BP = m_model.createIndividual( "http://www.geonames.org/ontology#S.BP", Code );
    
    public static final Individual L_CMN = m_model.createIndividual( "http://www.geonames.org/ontology#L.CMN", Code );
    
    public static final Individual H_LKS = m_model.createIndividual( "http://www.geonames.org/ontology#H.LKS", Code );
    
    public static final Individual U_CRSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.CRSU", Code );
    
    public static final Individual H_WHRL = m_model.createIndividual( "http://www.geonames.org/ontology#H.WHRL", Code );
    
    public static final Individual S_HLT = m_model.createIndividual( "http://www.geonames.org/ontology#S.HLT", Code );
    
    public static final Individual H_DTCH = m_model.createIndividual( "http://www.geonames.org/ontology#H.DTCH", Code );
    
    public static final Individual S_AGRF = m_model.createIndividual( "http://www.geonames.org/ontology#S.AGRF", Code );
    
    public static final Individual U_TNGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TNGU", Code );
    
    public static final Individual L_GASF = m_model.createIndividual( "http://www.geonames.org/ontology#L.GASF", Code );
    
    public static final Individual T_PASS = m_model.createIndividual( "http://www.geonames.org/ontology#T.PASS", Code );
    
    public static final Individual S_CTRCM = m_model.createIndividual( "http://www.geonames.org/ontology#S.CTRCM", Code );
    
    public static final Individual T_PKS = m_model.createIndividual( "http://www.geonames.org/ontology#T.PKS", Code );
    
    public static final Individual R_RD = m_model.createIndividual( "http://www.geonames.org/ontology#R.RD", Code );
    
    public static final Individual L_FLDI = m_model.createIndividual( "http://www.geonames.org/ontology#L.FLDI", Code );
    
    public static final Individual R_STKR = m_model.createIndividual( "http://www.geonames.org/ontology#R.STKR", Code );
    
    public static final Individual H_PNDI = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDI", Code );
    
    public static final Individual H_BNKX = m_model.createIndividual( "http://www.geonames.org/ontology#H.BNKX", Code );
    
    public static final Individual R_RDCUT = m_model.createIndividual( "http://www.geonames.org/ontology#R.RDCUT", Code );
    
    public static final Individual L_CST = m_model.createIndividual( "http://www.geonames.org/ontology#L.CST", Code );
    
    public static final Individual U_SPRU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SPRU", Code );
    
    public static final Individual H_FJDS = m_model.createIndividual( "http://www.geonames.org/ontology#H.FJDS", Code );
    
    public static final Individual L_RGNL = m_model.createIndividual( "http://www.geonames.org/ontology#L.RGNL", Code );
    
    public static final Individual S_GOSP = m_model.createIndividual( "http://www.geonames.org/ontology#S.GOSP", Code );
    
    public static final Individual T_PLATX = m_model.createIndividual( "http://www.geonames.org/ontology#T.PLATX", Code );
    
    public static final Individual S_PYRS = m_model.createIndividual( "http://www.geonames.org/ontology#S.PYRS", Code );
    
    public static final Individual L_BSNP = m_model.createIndividual( "http://www.geonames.org/ontology#L.BSNP", Code );
    
    public static final Individual S_PIER = m_model.createIndividual( "http://www.geonames.org/ontology#S.PIER", Code );
    
    public static final Individual T_DPR = m_model.createIndividual( "http://www.geonames.org/ontology#T.DPR", Code );
    
    public static final Individual S_PMPO = m_model.createIndividual( "http://www.geonames.org/ontology#S.PMPO", Code );
    
    public static final Individual U_FRSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FRSU", Code );
    
    public static final Individual H_PNDN = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDN", Code );
    
    public static final Individual H_FISH = m_model.createIndividual( "http://www.geonames.org/ontology#H.FISH", Code );
    
    public static final Individual L_INDS = m_model.createIndividual( "http://www.geonames.org/ontology#L.INDS", Code );
    
    public static final Individual S_HSTS = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSTS", Code );
    
    public static final Individual T_KRST = m_model.createIndividual( "http://www.geonames.org/ontology#T.KRST", Code );
    
    public static final Individual U_LDGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.LDGU", Code );
    
    public static final Individual T_FORD = m_model.createIndividual( "http://www.geonames.org/ontology#T.FORD", Code );
    
    public static final Individual S_HSPL = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSPL", Code );
    
    public static final Individual T_BLDR = m_model.createIndividual( "http://www.geonames.org/ontology#T.BLDR", Code );
    
    public static final Individual S_SNTR = m_model.createIndividual( "http://www.geonames.org/ontology#S.SNTR", Code );
    
    public static final Individual T_BLOW = m_model.createIndividual( "http://www.geonames.org/ontology#T.BLOW", Code );
    
    public static final Individual R_PTGE = m_model.createIndividual( "http://www.geonames.org/ontology#R.PTGE", Code );
    
    public static final Individual T_PT = m_model.createIndividual( "http://www.geonames.org/ontology#T.PT", Code );
    
    public static final Individual T_PANS = m_model.createIndividual( "http://www.geonames.org/ontology#T.PANS", Code );
    
    public static final Individual H_OCN = m_model.createIndividual( "http://www.geonames.org/ontology#H.OCN", Code );
    
    public static final Individual U_MESU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MESU", Code );
    
    public static final Individual S_DAMQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.DAMQ", Code );
    
    public static final Individual S_MLSGQ = m_model.createIndividual( "http://www.geonames.org/ontology#S.MLSGQ", Code );
    
    public static final Individual U_PLTU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PLTU", Code );
    
    public static final Individual T_VALG = m_model.createIndividual( "http://www.geonames.org/ontology#T.VALG", Code );
    
    public static final Individual V_CULT = m_model.createIndividual( "http://www.geonames.org/ontology#V.CULT", Code );
    
    public static final Individual R_OILP = m_model.createIndividual( "http://www.geonames.org/ontology#R.OILP", Code );
    
    public static final Individual S_LOCK = m_model.createIndividual( "http://www.geonames.org/ontology#S.LOCK", Code );
    
    public static final Individual U_RDGU = m_model.createIndividual( "http://www.geonames.org/ontology#U.RDGU", Code );
    
    public static final Individual S_INSM = m_model.createIndividual( "http://www.geonames.org/ontology#S.INSM", Code );
    
    public static final Individual S_DIKE = m_model.createIndividual( "http://www.geonames.org/ontology#S.DIKE", Code );
    
    public static final Individual H_PNDS = m_model.createIndividual( "http://www.geonames.org/ontology#H.PNDS", Code );
    
    public static final Individual U_TMSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.TMSU", Code );
    
    public static final Individual S_HSE = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSE", Code );
    
    public static final Individual H_WTLDI = m_model.createIndividual( "http://www.geonames.org/ontology#H.WTLDI", Code );
    
    public static final Individual U_FRKU = m_model.createIndividual( "http://www.geonames.org/ontology#U.FRKU", Code );
    
    public static final Individual U_MTSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MTSU", Code );
    
    public static final Individual U_SHVU = m_model.createIndividual( "http://www.geonames.org/ontology#U.SHVU", Code );
    
    public static final Individual L_QCKS = m_model.createIndividual( "http://www.geonames.org/ontology#L.QCKS", Code );
    
    public static final Individual T_CLF = m_model.createIndividual( "http://www.geonames.org/ontology#T.CLF", Code );
    
    public static final Individual R_RDJCT = m_model.createIndividual( "http://www.geonames.org/ontology#R.RDJCT", Code );
    
    public static final Individual S_ZNF = m_model.createIndividual( "http://www.geonames.org/ontology#S.ZNF", Code );
    
    public static final Individual T_HLL = m_model.createIndividual( "http://www.geonames.org/ontology#T.HLL", Code );
    
    public static final Individual H_SILL = m_model.createIndividual( "http://www.geonames.org/ontology#H.SILL", Code );
    
    public static final Individual S_PSTB = m_model.createIndividual( "http://www.geonames.org/ontology#S.PSTB", Code );
    
    public static final Individual U_KNLU = m_model.createIndividual( "http://www.geonames.org/ontology#U.KNLU", Code );
    
    public static final Individual L_ZZZZZ = m_model.createIndividual( "http://www.geonames.org/ontology#L.ZZZZZ", Code );
    
    public static final Individual H_BOG = m_model.createIndividual( "http://www.geonames.org/ontology#H.BOG", Code );
    
    public static final Individual V_SCRB = m_model.createIndividual( "http://www.geonames.org/ontology#V.SCRB", Code );
    
    public static final Individual T_PLAT = m_model.createIndividual( "http://www.geonames.org/ontology#T.PLAT", Code );
    
    public static final Individual S_NSY = m_model.createIndividual( "http://www.geonames.org/ontology#S.NSY", Code );
    
    public static final Individual S_CMP = m_model.createIndividual( "http://www.geonames.org/ontology#S.CMP", Code );
    
    public static final Individual H_DCKB = m_model.createIndividual( "http://www.geonames.org/ontology#H.DCKB", Code );
    
    public static final Individual S_TRMO = m_model.createIndividual( "http://www.geonames.org/ontology#S.TRMO", Code );
    
    public static final Individual T_PLDR = m_model.createIndividual( "http://www.geonames.org/ontology#T.PLDR", Code );
    
    public static final Individual S_BLDG = m_model.createIndividual( "http://www.geonames.org/ontology#S.BLDG", Code );
    
    public static final Individual H_RSV = m_model.createIndividual( "http://www.geonames.org/ontology#H.RSV", Code );
    
    public static final Individual S_PSTC = m_model.createIndividual( "http://www.geonames.org/ontology#S.PSTC", Code );
    
    public static final Individual S_CH = m_model.createIndividual( "http://www.geonames.org/ontology#S.CH", Code );
    
    public static final Individual S_CSNO = m_model.createIndividual( "http://www.geonames.org/ontology#S.CSNO", Code );
    
    public static final Individual T_CRTR = m_model.createIndividual( "http://www.geonames.org/ontology#T.CRTR", Code );
    
    public static final Individual R_RYD = m_model.createIndividual( "http://www.geonames.org/ontology#R.RYD", Code );
    
    public static final Individual S_HSP = m_model.createIndividual( "http://www.geonames.org/ontology#S.HSP", Code );
    
    public static final Individual S_RSGNL = m_model.createIndividual( "http://www.geonames.org/ontology#S.RSGNL", Code );
    
    public static final Individual L_GRAZ = m_model.createIndividual( "http://www.geonames.org/ontology#L.GRAZ", Code );
    
    public static final Individual U_PKSU = m_model.createIndividual( "http://www.geonames.org/ontology#U.PKSU", Code );
    
    public static final Individual H_GYSR = m_model.createIndividual( "http://www.geonames.org/ontology#H.GYSR", Code );
    
    public static final Individual S_SHPF = m_model.createIndividual( "http://www.geonames.org/ontology#S.SHPF", Code );
    
    public static final Individual T_VAL = m_model.createIndividual( "http://www.geonames.org/ontology#T.VAL", Code );
    
    public static final Individual V_TUND = m_model.createIndividual( "http://www.geonames.org/ontology#V.TUND", Code );
    
    public static final Individual R_RJCT = m_model.createIndividual( "http://www.geonames.org/ontology#R.RJCT", Code );
    
    public static final Individual U_MTU = m_model.createIndividual( "http://www.geonames.org/ontology#U.MTU", Code );
    
    public static final Individual T_RDGB = m_model.createIndividual( "http://www.geonames.org/ontology#T.RDGB", Code );
    
    public static final Individual H_ANCH = m_model.createIndividual( "http://www.geonames.org/ontology#H.ANCH", Code );
    
    public static final Individual L_CLG = m_model.createIndividual( "http://www.geonames.org/ontology#L.CLG", Code );
    
    public static final Individual T_PLN = m_model.createIndividual( "http://www.geonames.org/ontology#T.PLN", Code );
    
    public static final Individual T_CRQS = m_model.createIndividual( "http://www.geonames.org/ontology#T.CRQS", Code );
    
}
